// Deployer Obligations Tool - Art.26 Obligations of Deployers
// Client Component: 8-item checklist with auto-save, progress bar, and report generation

"use client";

import { useState, useEffect, useCallback } from "react";
import { useTranslations } from "next-intl";

interface AISystem {
  id: string;
  name: string;
  art26Compliant?: boolean;
}

interface ObligationItem {
  id: string;
  articleRef: string;
  title: string;
  description: string;
  legalText: string;
}

const OBLIGATIONS: ObligationItem[] = [
  {
    id: "instructionsOfUse",
    articleRef: "Art.26(1)",
    title: "Use in Accordance with Instructions of Use",
    description:
      "Deployers of high-risk AI systems must use the system in accordance with the instructions of use accompanying the system.",
    legalText:
      "Article 26(1): Deployers of high-risk AI systems shall use the system in accordance with the instructions of use accompanying the system, pursuant to Article 13(4).",
  },
  {
    id: "humanOversight",
    articleRef: "Art.26(2)",
    title: "Ensure Human Oversight Is in Place",
    description:
      "Deployers shall assign to natural persons the competence, training, authority, and tools necessary to ensure effective oversight of the AI system during operation.",
    legalText:
      "Article 26(2): Deployers of high-risk AI systems shall assign to natural persons the competence, training and authority as well as the tools necessary to ensure effective oversight of the AI system during operation in accordance with Article 14(2).",
  },
  {
    id: "monitorOperation",
    articleRef: "Art.26(3)",
    title: "Monitor Operation of the High-Risk AI System",
    description:
      "Deployers shall monitor the operation of the high-risk AI system and, where relevant, inform the provider about identified risks, serious incidents, or malfunctioning.",
    legalText:
      "Article 26(3): Deployers of high-risk AI systems shall monitor the operation of the high-risk AI system referred to in paragraph 1 and, where relevant, inform the provider about identified risks, serious incidents or malfunctioning of that system in accordance with Article 72.",
  },
  {
    id: "keepLogs",
    articleRef: "Art.26(4)",
    title: "Keep Logs Automatically Generated by the AI System",
    description:
      "Deployers shall keep the logs automatically generated by the high-risk AI system for an appropriate period that is proportionate to the intended purpose and in accordance with applicable sector-specific rules.",
    legalText:
      "Article 26(4): Deployers of high-risk AI systems shall keep the logs automatically generated by that high-risk AI system, to the extent such logs are under their control, for an appropriate period that is proportionate to the intended purpose of the high-risk AI system and in accordance with applicable sector-specific rules and legislation.",
  },
  {
    id: "informSeriousIncidents",
    articleRef: "Art.26(5)",
    title: "Inform the Provider About Serious Incidents",
    description:
      "Deployers shall, without undue delay, inform the provider of the high-risk AI system and, where applicable, the relevant market surveillance authority about any serious incident.",
    legalText:
      "Article 26(5): Deployers of high-risk AI systems shall, without undue delay, inform the provider of the high-risk AI system and, where applicable, importers or distributors and the relevant market surveillance authorities referred to in Article 74(1) where they identify a serious incident or a malfunctioning of the system and where applicable, they shall inform the national public authority referred to in Article 66(2) of that serious incident.",
  },
  {
    id: "fundamentalRightsImpactAssessment",
    articleRef: "Art.26(6)",
    title: "Carry Out Fundamental Rights Impact Assessment Before First Use",
    description:
      "Deployers that are bodies governed by public law or private entities providing public services must carry out a fundamental rights impact assessment before putting a high-risk AI system into use for the first time.",
    legalText:
      "Article 26(6): Before putting into service or use a high-risk AI system listed in Annex III at the workplace or for access to essential private and public services and benefits, deployers that are bodies governed by public law or private entities providing public services and benefits shall perform a fundamental rights impact assessment.",
  },
  {
    id: "competentOversight",
    articleRef: "Art.26(7)",
    title: "Ensure Persons in Charge of Oversight Are Competent",
    description:
      "Deployers shall ensure that the natural persons assigned to oversee the high-risk AI system have the necessary competence, training, authority, and level of independence.",
    legalText:
      "Article 26(7): Deployers of high-risk AI systems shall ensure that the natural persons assigned to oversee the high-risk AI system have the necessary competence, training, authority and level of independence to carry out their tasks effectively and to interpret the system's output correctly.",
  },
  {
    id: "accessibility",
    articleRef: "Art.26(8)",
    title: "Ensure Accessibility for Persons with Disabilities",
    description:
      "Deployers shall ensure that the use of the high-risk AI system does not prevent the accessibility of services for persons with disabilities.",
    legalText:
      "Article 26(8): Deployers of high-risk AI systems shall ensure that the use of the high-risk AI system does not lead to a restriction of the rights of persons with disabilities to access essential private and public services and benefits.",
  },
];

interface ChecklistState {
  [key: string]: boolean;
}

const DEFAULT_CHECKLIST: ChecklistState = Object.fromEntries(
  OBLIGATIONS.map((o) => [o.id, false])
);

export default function DeployerObligationsPage() {
  const t = useTranslations();

  const [systems, setSystems] = useState<AISystem[]>([]);
  const [selectedSystemId, setSelectedSystemId] = useState<string>("");
  const [checklist, setChecklist] = useState<ChecklistState>(DEFAULT_CHECKLIST);
  const [isLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [saveMessage, setSaveMessage] = useState("");
  const [showReport, setShowReport] = useState(false);
  const [expandedItems, setExpandedItems] = useState<Set<string>>(new Set());

  // Fetch user's AI systems
  const fetchSystems = useCallback(async () => {
    try {
      const res = await fetch("/api/ai-systems");
      if (res.ok) {
        const data = await res.json();
        setSystems(data.data ?? []);
      }
    } catch (error) {
      console.error("[DEPLOYER-OBLIGATIONS] Failed to fetch systems:", error);
    }
  }, []);

  useEffect(() => {
    fetchSystems();
  }, [fetchSystems]);

  // Load existing compliance state when system is selected
  useEffect(() => {
    if (!selectedSystemId) {
      setChecklist(DEFAULT_CHECKLIST);
      return;
    }
    const system = systems.find((s) => s.id === selectedSystemId);
    if (system?.art26Compliant) {
      // If fully compliant, mark all items as checked
      setChecklist(Object.fromEntries(OBLIGATIONS.map((o) => [o.id, true])));
    } else {
      setChecklist(DEFAULT_CHECKLIST);
    }
    setShowReport(false);
    setExpandedItems(new Set());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedSystemId]);

  // Auto-save on toggle via PATCH /api/ai-systems/[id]
  const saveState = useCallback(
    async (updated: ChecklistState) => {
      if (!selectedSystemId) return;
      setIsSaving(true);
      setSaveMessage("");
      try {
        const allChecked = OBLIGATIONS.every((o) => updated[o.id]);
        const res = await fetch(`/api/ai-systems/${selectedSystemId}`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ art26Compliant: allChecked }),
        });
        if (res.ok) {
          setSaveMessage(t("tools.saved"));
          setTimeout(() => setSaveMessage(""), 1500);
        } else {
          setSaveMessage(t("tools.errorSaving"));
        }
      } catch (error) {
        console.error("[DEPLOYER-OBLIGATIONS] Auto-save failed:", error);
        setSaveMessage(t("tools.errorSaving"));
      } finally {
        setIsSaving(false);
      }
    },
    [selectedSystemId]
  );

  const handleToggle = (id: string) => {
    setChecklist((prev) => {
      const updated = { ...prev, [id]: !prev[id] };
      return updated;
    });
  };

  // Debounced auto-save
  useEffect(() => {
    if (!selectedSystemId) return;
    const timer = setTimeout(() => {
      saveState(checklist);
    }, 600);
    return () => clearTimeout(timer);
  }, [checklist, selectedSystemId, saveState]);

  const toggleExpand = (id: string) => {
    setExpandedItems((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const checkedCount = OBLIGATIONS.filter((o) => checklist[o.id]).length;
  const progress = Math.round((checkedCount / OBLIGATIONS.length) * 100);
  const selectedSystem = systems.find((s) => s.id === selectedSystemId);

  return (
    <div className="container mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      {/* Header */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <span className="rounded bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
            Art. 26
          </span>
          <span className="rounded-full bg-orange-500/10 px-2 py-0.5 text-xs font-medium text-orange-600">{t("tools.results")}          </span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight">
          Deployer Obligations Checklist
        </h1>
        <p className="text-sm text-muted-foreground">
          Verify your compliance with the 8 deployer obligations under Article 26
          of the EU AI Act. Changes are automatically saved to your AI system
          record.
        </p>
      </div>

      {/* System Selector */}
      <div className="mt-8">
        <label
          htmlFor="system-select"
          className="block text-sm font-medium"
        >{t("tools.selectSystem")}        </label>
        <select
          id="system-select"
          value={selectedSystemId}
          onChange={(e) => setSelectedSystemId(e.target.value)}
          className="mt-1 block w-full rounded-md border border-border bg-background px-3 py-2 text-sm"
        >
          <option value="">{t("tools.selectSystem")}</option>
          {systems.map((s) => (
            <option key={s.id} value={s.id}>
              {s.name}
            </option>
          ))}
        </select>
        {systems.length === 0 && (
          <p className="mt-2 text-xs text-muted-foreground">
            {t("tools.noSystems")}
          </p>
        )}
      </div>

      {selectedSystemId && (
        <>
          {/* Progress Bar */}
          <div className="mt-8">
            <div className="flex items-center justify-between text-sm">
              <span className="text-muted-foreground">
                {checkedCount} / {OBLIGATIONS.length} obligations completed
              </span>
              <span className="text-muted-foreground">{progress}%</span>
            </div>
            <div className="mt-2 h-2 w-full rounded-full bg-muted">
              <div
                className={`h-2 rounded-full transition-all ${
                  progress === 100 ? "bg-accent" : "bg-primary"
                }`}
                style={{ width: `${progress}%` }}
              />
            </div>
            {(saveMessage || isSaving) && (
              <p className="mt-1 text-xs text-muted-foreground">
                {isSaving ? "Saving..." : saveMessage}
              </p>
            )}
          </div>

          {/* Checklist */}
          {isLoading ? (
            <div className="mt-8 flex items-center justify-center py-8">
              <div className="h-6 w-6 animate-spin rounded-full border-2 border-primary border-t-transparent" />
            </div>
          ) : (
            <div className="mt-8 space-y-3">
              {OBLIGATIONS.map((obligation) => {
                const isChecked = checklist[obligation.id];
                const isExpanded = expandedItems.has(obligation.id);

                return (
                  <div
                    key={obligation.id}
                    className={`rounded-lg border transition-colors ${
                      isChecked
                        ? "border-accent/30 bg-accent/5"
                        : "border-border bg-background"
                    }`}
                  >
                    <label className="flex cursor-pointer items-start gap-3 p-4">
                      <input
                        type="checkbox"
                        checked={isChecked}
                        onChange={() => handleToggle(obligation.id)}
                        className="mt-1 h-4 w-4 rounded border-border text-primary focus:ring-primary"
                      />
                      <div className="flex-1">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <span className="text-sm font-medium">
                              {obligation.title}
                            </span>
                            <span className="rounded bg-primary/10 px-1.5 py-0.5 text-xs font-medium text-primary">
                              {obligation.articleRef}
                            </span>
                          </div>
                          {isChecked && (
                            <span className="rounded bg-accent/10 px-1.5 py-0.5 text-xs font-medium text-accent">{t("tools.saved")}                            </span>
                          )}
                        </div>
                        <p className="mt-1 text-xs text-muted-foreground">
                          {obligation.description}
                        </p>
                      </div>
                    </label>

                    {/* Expandable Legal Text */}
                    <div className="border-t border-border">
                      <button
                        type="button"
                        onClick={() => toggleExpand(obligation.id)}
                        className="flex w-full items-center justify-between px-4 py-2 text-xs text-muted-foreground transition-colors hover:bg-muted/30"
                      >
                        <span>{isExpanded ? "Hide legal text" : "Show legal text"}</span>
                        <svg
                          className={`h-4 w-4 transition-transform ${isExpanded ? "rotate-180" : ""}`}
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          strokeWidth={2}
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                          />
                        </svg>
                      </button>
                      {isExpanded && (
                        <div className="border-t border-border bg-muted/20 px-4 py-3">
                          <p className="text-xs leading-relaxed text-muted-foreground italic">
                            {obligation.legalText}
                          </p>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {/* Generate Report */}
          <div className="mt-8">
            <button
              type="button"
              onClick={() => setShowReport(true)}
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
            >
              Generate Report
            </button>
          </div>

          {/* Report Summary */}
          {showReport && (
            <div className="mt-8 rounded-lg border border-border bg-muted/30 p-6">
              <h2 className="text-xl font-semibold">
                Art.26 Deployer Obligations Report
              </h2>
              <p className="mt-1 text-xs text-muted-foreground">
                Generated for: {selectedSystem?.name ?? "Unknown System"}
              </p>

              <div className="mt-4 space-y-4">
                {/* Completion Overview */}
                <div className="flex items-center gap-3">
                  <span className="text-sm text-muted-foreground">
                    Completion:
                  </span>
                  <span className="text-2xl font-bold">{progress}%</span>
                  <span
                    className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${
                      progress === 100
                        ? "bg-accent/10 text-accent"
                        : "bg-orange-500/10 text-orange-600"
                    }`}
                  >
                    {progress === 100 ? "Fully Compliant" : "Incomplete"}
                  </span>
                </div>

                {/* Obligations Summary */}
                <div className="rounded-md border border-border bg-background p-4">
                  <h3 className="text-sm font-semibold">Obligations Summary</h3>
                  <ul className="mt-2 space-y-2">
                    {OBLIGATIONS.map((obligation) => (
                      <li
                        key={obligation.id}
                        className="flex items-center gap-2 text-sm"
                      >
                        <span
                          className={`flex h-4 w-4 items-center justify-center rounded-full text-[10px] font-bold ${
                            checklist[obligation.id]
                              ? "bg-accent text-white"
                              : "bg-muted text-muted-foreground"
                          }`}
                        >
                          {checklist[obligation.id] ? "\u2713" : "\u25CB"}
                        </span>
                        <span
                          className={
                            checklist[obligation.id]
                              ? "text-foreground"
                              : "text-muted-foreground"
                          }
                        >
                          {obligation.title} ({obligation.articleRef})
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Action Required */}
                {progress < 100 && (
                  <div className="rounded-md border border-orange-200 bg-orange-50 p-4 text-sm text-orange-800">
                    <strong>Action Required:</strong> Complete the remaining{" "}
                    {OBLIGATIONS.length - checkedCount} obligation(s) to achieve
                    full Art.26 deployer compliance. Ensure all deployer
                    obligations are met before putting the high-risk AI system
                    into use.
                  </div>
                )}

                {progress === 100 && (
                  <div className="rounded-md border border-accent/30 bg-accent/5 p-4 text-sm text-accent">
                    <strong>Compliance Achieved:</strong> All 8 Art.26 deployer
                    obligations have been verified. The system record has been
                    updated to reflect full compliance.
                  </div>
                )}

                {/* Print Button */}
                <button
                  type="button"
                  onClick={() => window.print()}
                  className="inline-flex h-10 items-center justify-center rounded-md border border-border px-4 text-sm font-medium transition-colors hover:bg-muted"
                >{t("tools.download")}                </button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
