// Art.50 Transparency Obligations Check
// Client Component: 5-point checklist for transparency compliance
// Starter tier feature (€39/month)

"use client";

import { useState, useCallback } from "react";
import { useTranslations } from "next-intl";

/**
 * Answer state for each item: compliant, non-compliant, or not applicable
 */
type TransparencyAnswer = "compliant" | "non-compliant" | "not-applicable" | null;

/**
 * Individual transparency check item
 */
interface TransparencyItem {
  id: string;
  title: string;
  description: string;
  requirement: string;
  articleRef: string;
}

/**
 * Art.50 transparency obligations checklist
 * 5 items covering all transparency requirements
 */
const TRANSPARENCY_ITEMS: TransparencyItem[] = [
  {
    id: "chatbot_disclosure",
    title: "Chatbot / Conversational AI Disclosure",
    description:
      "Users must be informed they are interacting with an AI system, unless obvious from context.",
    requirement:
      "Display clear notice before first interaction. Example: 'You are chatting with an AI assistant.'",
    articleRef: "Art.50(1)",
  },
  {
    id: "deepfake_labeling",
    title: "Deepfake / Synthetic Content Labeling",
    description:
      "AI-generated or manipulated content must be clearly labeled as artificially generated or manipulated.",
    requirement:
      "Apply visible watermarks or metadata markers. Disclose artificial nature to viewers.",
    articleRef: "Art.50(2)",
  },
  {
    id: "emotion_recognition",
    title: "Emotion Recognition Notification",
    description:
      "When AI systems detect or infer emotions, users must be informed of the system's operation.",
    requirement:
      "Provide explicit notification before emotion detection begins. Allow opt-out where possible.",
    articleRef: "Art.50(3)",
  },
  {
    id: "biometric_categorization",
    title: "Biometric Categorization Disclosure",
    description:
      "When AI systems categorize individuals based on biometric data, the operation must be disclosed.",
    requirement:
      "Inform individuals that biometric categorization is occurring and its purpose.",
    articleRef: "Art.50(3)",
  },
  {
    id: "ai_generated_content",
    title: "AI-Generated Text Publication",
    description:
      "Text published for informative purposes on matters of public interest must disclose AI generation.",
    requirement:
      "Add disclosure statement: 'This article was generated by artificial intelligence.'",
    articleRef: "Art.50(4)",
  },
];

/**
 * Art.50 Transparency Obligations Check Tool
 */
export default function TransparencyPage() {
  const t = useTranslations();

  const [answers, setAnswers] = useState<Record<string, TransparencyAnswer>>({});
  const [showResults, setShowResults] = useState(false);

  const handleAnswer = useCallback(
    (itemId: string, value: TransparencyAnswer) => {
      setAnswers((prev) => ({ ...prev, [itemId]: value }));
      if (showResults) setShowResults(false);
    },
    [showResults]
  );

  const answeredCount = Object.values(answers).filter(
    (a) => a !== null
  ).length;
  const allAnswered = answeredCount === TRANSPARENCY_ITEMS.length;

  const applicableItems = TRANSPARENCY_ITEMS.filter(
    (item) => answers[item.id] !== "not-applicable"
  );

  const compliantCount = applicableItems.filter(
    (item) => answers[item.id] === "compliant"
  ).length;

  const nonCompliantItems = applicableItems.filter(
    (item) => answers[item.id] === "non-compliant"
  );

  const notApplicableCount = TRANSPARENCY_ITEMS.filter(
    (item) => answers[item.id] === "not-applicable"
  ).length;

  const handleSubmit = useCallback(() => {
    if (!allAnswered) return;
    setShowResults(true);
  }, [allAnswered]);

  const handleReset = useCallback(() => {
    setAnswers({});
    setShowResults(false);
  }, []);

  const applicableTotal = applicableItems.length;
  const complianceRate =
    applicableTotal > 0
      ? Math.round((compliantCount / applicableTotal) * 100)
      : 0;

  return (
    <div className="container mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      {/* Header */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <span className="rounded bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
            Art. 50
          </span>
          <span className="text-xs text-muted-foreground">{t("tools.results")}</span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight">Transparency Obligations Check</h1>
        <p className="text-muted-foreground">
          Verify your AI system meets Article 50 transparency requirements.
          This 5-point checklist covers chatbot disclosure, deepfake labeling,
          emotion recognition notification, and more.
        </p>
      </div>

      {/* Progress */}
      <div className="mt-8">
        <div className="flex items-center justify-between text-sm">
          <span className="text-muted-foreground">
            {t("tools.results")} {answeredCount} / {TRANSPARENCY_ITEMS.length}
          </span>
          {allAnswered && (
            <span className="text-accent">{t("tools.results")}</span>
          )}
        </div>
        <div className="mt-2 h-2 w-full rounded-full bg-muted">
          <div
            className="h-2 rounded-full bg-primary transition-all"
            style={{
              width: `${(answeredCount / TRANSPARENCY_ITEMS.length) * 100}%`,
            }}
          />
        </div>
      </div>

      {/* Checklist */}
      <div className="mt-8 space-y-4">
        {TRANSPARENCY_ITEMS.map((item, index) => (
          <TransparencyCard
            key={item.id}
            index={index + 1}
            item={item}
            answer={answers[item.id] ?? null}
            onAnswer={handleAnswer}
          />
        ))}
      </div>

      {/* Actions */}
      <div className="mt-8 flex items-center gap-4">
        <button
          type="button"
          onClick={handleSubmit}
          disabled={!allAnswered}
          className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-6 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-50"
        >{t("tools.results")}        </button>
        <button
          type="button"
          onClick={handleReset}
          className="inline-flex h-10 items-center justify-center rounded-md border border-border px-6 text-sm font-medium transition-colors hover:bg-muted"
        >{t("common.reset")}        </button>
      </div>

      {/* Results */}
      {showResults && (
        <div className="mt-8 rounded-lg border border-border bg-muted/30 p-6">
          <h2 className="text-xl font-semibold">{t("tools.results")}          </h2>

          {/* Stats */}
          <div className="mt-4 grid gap-4 sm:grid-cols-3">
            <div className="rounded-md border border-accent/30 bg-accent/5 p-4">
              <p className="text-sm text-muted-foreground">{t("tools.compliant")}</p>
              <p className="text-3xl font-bold text-accent">
                {compliantCount}
              </p>
              <p className="mt-1 text-xs text-muted-foreground">
                out of {applicableTotal} applicable
              </p>
            </div>
            <div className="rounded-md border border-destructive/30 bg-destructive/5 p-4">
              <p className="text-sm text-muted-foreground">Non-Compliant</p>
              <p className="text-3xl font-bold text-destructive">
                {nonCompliantItems.length}
              </p>
              <p className="mt-1 text-xs text-muted-foreground">
                {t("tools.results")}
              </p>
            </div>
            <div className="rounded-md border border-border bg-muted/50 p-4">
              <p className="text-sm text-muted-foreground">{t("tools.notApplicable")}</p>
              <p className="text-3xl font-bold text-muted-foreground">
                {notApplicableCount}
              </p>
              <p className="mt-1 text-xs text-muted-foreground">
                {t("tools.results")}
              </p>
            </div>
          </div>

          {/* Compliance rate */}
          {applicableTotal > 0 && (
            <div className="mt-4">
              <div className="flex items-center justify-between text-sm">
                <span className="text-muted-foreground">{t("tools.results")}                </span>
                <span className="font-medium">{complianceRate}%</span>
              </div>
              <div className="mt-2 h-3 w-full rounded-full bg-muted">
                <div
                  className={`h-3 rounded-full transition-all ${
                    complianceRate === 100
                      ? "bg-accent"
                      : complianceRate >= 60
                      ? "bg-yellow-500"
                      : "bg-destructive"
                  }`}
                  style={{ width: `${complianceRate}%` }}
                />
              </div>
            </div>
          )}

          {/* Non-compliant details */}
          {nonCompliantItems.length > 0 && (
            <div className="mt-4 rounded-md border border-destructive/30 bg-destructive/5 p-4">
              <h3 className="text-sm font-semibold text-destructive">{t("tools.highRisk")}              </h3>
              <p className="mt-1 text-sm text-muted-foreground">
                The following transparency obligations are not yet met. Each
                missing item may result in regulatory penalties under Art.71.
              </p>
              <ul className="mt-3 space-y-3">
                {nonCompliantItems.map((item) => (
                  <li key={item.id} className="text-sm">
                    <div className="flex items-center gap-2">
                      <span className="h-1.5 w-1.5 rounded-full bg-destructive" />
                      <span className="font-medium">{item.title}</span>
                      <span className="text-xs text-muted-foreground">
                        ({item.articleRef})
                      </span>
                    </div>
                    <p className="mt-1 pl-3.5 text-muted-foreground">
                      Requirement: {item.requirement}
                    </p>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Fully compliant */}
          {nonCompliantItems.length === 0 && applicableTotal > 0 && (
            <div className="mt-4 rounded-md border border-accent/50 bg-accent/10 p-4">
              <h3 className="text-sm font-semibold text-accent">{t("tools.compliant")}              </h3>
              <p className="mt-1 text-sm text-muted-foreground">
                Your AI system meets all applicable Article 50 transparency
                obligations. Ensure these measures are maintained and
                documented as your system evolves.
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

/**
 * Individual transparency check card
 */
function TransparencyCard({
  index,
  item,
  answer,
  onAnswer,
}: {
  index: number;
  item: TransparencyItem;
  answer: TransparencyAnswer;
  onAnswer: (id: string, value: TransparencyAnswer) => void;
}) {
  return (
    <div className="rounded-lg border border-border bg-background p-5">
      <div className="flex items-start gap-3">
        <span className="mt-0.5 flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-muted text-xs font-medium">
          {index}
        </span>
        <div className="flex-1 space-y-2">
          <div className="flex items-center gap-2">
            <h3 className="text-sm font-semibold">{item.title}</h3>
            <span className="rounded bg-primary/10 px-1.5 py-0.5 text-xs font-medium text-primary">
              {item.articleRef}
            </span>
          </div>
          <p className="text-sm text-muted-foreground">
            {item.description}
          </p>
          <div className="rounded-md bg-muted/50 p-3">
            <p className="text-xs font-medium text-muted-foreground">
              Requirement
            </p>
            <p className="mt-0.5 text-xs text-muted-foreground">
              {item.requirement}
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2 pt-1">
            <button
              type="button"
              onClick={() => onAnswer(item.id, "compliant")}
              className={`inline-flex h-8 items-center justify-center rounded-md px-3 text-sm font-medium transition-colors ${
                answer === "compliant"
                  ? "bg-accent text-accent-foreground"
                  : "border border-border bg-background hover:bg-muted"
              }`}
            >Compliant            </button>
            <button
              type="button"
              onClick={() => onAnswer(item.id, "non-compliant")}
              className={`inline-flex h-8 items-center justify-center rounded-md px-3 text-sm font-medium transition-colors ${
                answer === "non-compliant"
                  ? "bg-destructive text-destructive-foreground"
                  : "border border-border bg-background hover:bg-muted"
              }`}
            >Not Compliant            </button>
            <button
              type="button"
              onClick={() => onAnswer(item.id, "not-applicable")}
              className={`inline-flex h-8 items-center justify-center rounded-md px-3 text-sm font-medium transition-colors ${
                answer === "not-applicable"
                  ? "bg-muted text-muted-foreground"
                  : "border border-border bg-background hover:bg-muted"
              }`}
            >Not Applicable            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
